'use client'

import Link from 'next/link'

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-gray-100">
      <div className="max-w-4xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="mb-12">
          <Link href="/" className="text-amber-500 hover:text-amber-400 mb-4 inline-block">
            ← Back to Home
          </Link>
          <h1 className="text-5xl font-bold text-white mb-4">Legal Disclaimer</h1>
          <p className="text-gray-400 text-lg">Last updated: June 2026</p>
        </div>

        {/* Critical Warning */}
        <div className="bg-red-900/40 border-2 border-red-500 rounded-lg p-8 mb-8">
          <h2 className="text-3xl font-bold text-red-400 mb-4">🚨 CRITICAL LEGAL DISCLAIMERS</h2>
          <p className="text-red-100 text-lg leading-relaxed mb-4">
            <strong>READ THIS CAREFULLY BEFORE USING VIRASAT.</strong>
          </p>
          <div className="space-y-4 text-red-100">
            <p>
              <strong>1. Virasat is NOT a legal Will, Trust, or court-recognized succession document.</strong>
              <br/>
              Your data stored in Virasat does NOT constitute a valid, legally binding Will under Indian law.
              Virasat is a <strong>storage and delivery tool only</strong>.
            </p>
            <p>
              <strong>2. Virasat does NOT transfer asset ownership.</strong>
              <br/>
              After delivery to beneficiaries, actual ownership transfer of bank accounts, property, cryptocurrency,
              gold, or other assets requires legal procedures (probate, succession certificate, bank forms, etc.).
            </p>
            <p>
              <strong>3. Virasat does NOT provide legal advice.</strong>
              <br/>
              Any content generated by Virasat (including AI-powered documents, templates, or guidance) is informational
              only and NOT a substitute for a qualified lawyer.
            </p>
            <p>
              <strong>4. You MUST consult a qualified lawyer.</strong>
              <br/>
              Before using Virasat, consult a lawyer licensed in your jurisdiction to ensure your estate plan complies
              with applicable succession laws.
            </p>
          </div>
        </div>

        {/* Main Content */}
        <div className="space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-3xl font-bold text-white mb-4">1. What Virasat Actually Is</h2>
            <p>
              Virasat is a zero-knowledge encrypted digital vault service that:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-2 mt-4">
              <li>Stores your encrypted personal, financial, and asset information</li>
              <li>Maintains a list of designated beneficiaries and executors</li>
              <li>Sends you periodic check-in reminders to verify you are alive</li>
              <li>Verifies death via executor's death certificate submission</li>
              <li>Delivers encrypted data to beneficiaries after death verification and a 30-day waiting period</li>
            </ul>
            <p className="mt-4">
              <strong>That's it. Virasat does NOTHING else.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">2. What Virasat Does NOT Do</h2>
            <p className="text-red-200 font-semibold mb-4">
              VIRASAT DOES NOT:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-3 text-red-100">
              <li>
                <strong>Replace a Will or legal estate plan.</strong> Your Virasat vault is NOT a legal Will
                recognized by courts, registrars, or financial institutions. It does not comply with the Indian Succession Act, 1925.
              </li>
              <li>
                <strong>Provide legal advice.</strong> Nothing in Virasat (templates, AI-generated content, guidance) is
                legal advice. Consulting a lawyer is your responsibility.
              </li>
              <li>
                <strong>Transfer asset ownership.</strong> Virasat does NOT access bank accounts, move money, change
                nominees, transfer property, or move cryptocurrency. These require separate legal procedures.
              </li>
              <li>
                <strong>File legal documents.</strong> Virasat does NOT file your Will, register property documents, or
                create succession certificates. This is your responsibility via proper legal channels.
              </li>
              <li>
                <strong>Resolve succession disputes.</strong> If family members or co-owners dispute your asset distribution,
                Virasat does NOT intervene. Legal courts will decide.
              </li>
              <li>
                <strong>Enforce succession law.</strong> Virasat does NOT check if your beneficiary designations comply
                with Hindu Succession Act, Muslim Personal Law, or other applicable statutes. This is your lawyer's job.
              </li>
              <li>
                <strong>Guarantee data delivery.</strong> If your executor is unavailable, death certificate is forged,
                or recovery shares are lost, Virasat cannot deliver your data.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">3. Indian Succession Laws & Your Obligations</h2>
            <p>
              India has multiple succession laws depending on religion and domicile. Virasat provides general guidance only:
            </p>

            <div className="bg-slate-700/50 rounded p-6 mt-4 space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-white mb-2">👥 Hindu Succession Act, 1956 (Amended)</h3>
                <p className="text-sm">
                  Applies to Hindus, Buddhists, Jains, and Sikhs. Defines legal heirs and succession hierarchy.
                  <strong> Your Virasat beneficiary choices may NOT match legal heirs.</strong> Consult a lawyer.
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-white mb-2">☪️ Muslim Personal Law (Shariat) Application Act, 1937</h3>
                <p className="text-sm">
                  Applies to Muslims. Follows Islamic succession principles (daughter gets 1/2 share of son, widow gets 1/8, etc.).
                  <strong> Virasat beneficiary designations must comply with Shariat.</strong> Consult a lawyer.
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-white mb-2">✝️ Indian Succession Act, 1925 (Sections 1-198)</h3>
                <p className="text-sm">
                  Applies to Christians and others. Allows testamentary freedom but must comply with formal will creation.
                  <strong> Your Virasat instructions are NOT a legal Will.</strong> Create a formal Will through a lawyer.
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold text-white mb-2">🏛️ Waqf Act, 1995 (Muslim Endowments)</h3>
                <p className="text-sm">
                  If you have waqf property or charitable endowments, Virasat does NOT handle these. Separate legal procedures apply.
                </p>
              </div>
            </div>

            <p className="mt-6 font-semibold text-yellow-300">
              ⚠️ YOUR RESPONSIBILITY: Consult a lawyer licensed in your jurisdiction to ensure your Virasat beneficiary
              designations and any actual Wills/Trusts comply with applicable succession law.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">4. AI-Generated Content & Legal Documents</h2>
            <p>
              Virasat may provide AI-powered templates or document drafting (using GPT-4):
            </p>
            <ul className="list-disc list-inside ml-4 space-y-2 mt-4">
              <li>
                <strong>NOT legal advice:</strong> AI-generated Wills, letters, or guidance are template suggestions only
              </li>
              <li>
                <strong>NOT customized for you:</strong> AI does not know your full circumstances, dependencies, debts, or family dynamics
              </li>
              <li>
                <strong>NOT court-ready without a lawyer:</strong> A lawyer must review and revise before you use AI-generated documents
              </li>
              <li>
                <strong>NOT binding:</strong> Using Virasat AI content does not create a legally valid Will without proper signing,
                witnessing, and registration per Indian law
              </li>
            </ul>
            <p className="mt-4 text-yellow-300">
              <strong>ALWAYS have a lawyer review any AI-generated content before relying on it.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">5. Data Loss Risks — Master Password & Recovery Shares</h2>
            <p className="text-yellow-300 font-semibold mb-4">
              ⚠️ <strong>IF YOU LOSE YOUR MASTER PASSWORD AND RECOVERY SHARES, YOUR DATA IS PERMANENTLY LOST AND CANNOT BE RECOVERED BY ANYONE.</strong>
            </p>
            <p className="mt-4">
              Virasat uses Shamir Secret Sharing:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-2 mt-2">
              <li><strong>Share 1:</strong> Stored on Virasat servers (encrypted with our key — we cannot access it)</li>
              <li><strong>Share 2:</strong> Given to your executor (QR code — they must keep it safe)</li>
              <li><strong>Share 3:</strong> For you to write down and store safely</li>
            </ul>
            <p className="mt-4">
              <strong>To recover your master password, any 2 of these 3 shares are needed.</strong>
            </p>
            <p className="mt-4 text-yellow-300">
              <strong>If you lose all 3 shares:</strong> Your data is PERMANENTLY encrypted and inaccessible.
              Virasat cannot help you. Not even a government agency or hacker can access it.
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">6. Executor Verification & Death Certificate</h2>
            <p className="text-yellow-300 font-semibold mb-4">
              <strong>⚠️ Death certificate forgery is possible. Virasat does NOT verify authenticity via government databases.</strong>
            </p>
            <p className="mt-4">
              Data is delivered after:
            </p>
            <ol className="list-decimal list-inside ml-4 space-y-2 mt-2">
              <li>Executor submits death certificate to Virasat</li>
              <li>Virasat team manually reviews (basic visual check — NOT forensic verification)</li>
              <li>30-day waiting period begins (to allow legal challenges)</li>
              <li>Data delivered to beneficiaries encrypted</li>
            </ol>
            <p className="mt-4">
              <strong>If someone forges a death certificate, this is a criminal matter outside Virasat's scope.</strong>
            </p>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">7. Liability & What Happens If Things Go Wrong</h2>
            <p className="text-red-200 font-semibold mb-4">
              VIRASAT IS PROVIDED "AS-IS" AND "AS-AVAILABLE." WE ARE NOT LIABLE FOR:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-2 text-red-100">
              <li>Data loss, corruption, or inaccessibility due to technical failures or cyberattacks</li>
              <li>Failure to deliver data (executor unavailable, lost shares, forged death certificate, etc.)</li>
              <li>Losses from legal disputes, succession conflicts, or incorrect beneficiary designations</li>
              <li>Asset losses from not having a proper legal Will or successor not claiming assets in time</li>
              <li>Identity theft, unauthorized access, or data breaches (despite encryption)</li>
              <li>Loss of business, revenue, or profits from using Virasat</li>
              <li>Indirect, incidental, or consequential damages</li>
            </ul>
          </section>

          <section>
            <h2 className="text-3xl font-bold text-white mb-4">8. Before You Use Virasat — Your Checklist</h2>
            <p className="text-green-200 font-semibold mb-4">
              ✅ DO THESE BEFORE OR WHILE USING VIRASAT:
            </p>
            <ul className="list-disc list-inside ml-4 space-y-3 text-green-100">
              <li><strong>Consult a qualified lawyer</strong> licensed in your state/country about your estate plan</li>
              <li><strong>Create a legal Will</strong> with a lawyer (don't rely on Virasat AI templates alone)</li>
              <li><strong>Register your Will</strong> with a probate court or registry office (if required)</li>
              <li><strong>Update nominees</strong> at banks, insurance companies, and investment firms</li>
              <li><strong>Understand your succession law</strong> (Hindu Succession Act, Muslim Personal Law, etc.)</li>
              <li><strong>Keep recovery shares safe</strong> (your Virasat share 3 + executor's share 2)</li>
              <li><strong>Keep your master password secure</strong> (memorize it or store in a safe place)</li>
              <li><strong>Inform family members</strong> about Virasat and how to access your vault</li>
              <li><strong>Review and update regularly</strong> as your family situation or wishes change</li>
            </ul>
          </section>

          {/* Final Acknowledgment */}
          <div className="bg-red-900/30 border-2 border-red-500 rounded-lg p-6 mt-12">
            <h3 className="text-2xl font-bold text-red-400 mb-4">📜 Final Acknowledgment</h3>
            <p className="text-red-100 leading-relaxed mb-4">
              <strong>By using Virasat, you acknowledge that you have read and understood these disclaimers:</strong>
            </p>
            <ul className="list-disc list-inside text-red-100 space-y-2">
              <li>Virasat is a storage tool only, NOT a legal Will or estate plan</li>
              <li>Virasat does NOT transfer asset ownership automatically</li>
              <li>Virasat does NOT provide legal advice</li>
              <li>You will consult a qualified lawyer for your estate plan</li>
              <li>You accept all risks and limitations of Virasat</li>
              <li>You accept that losing master password + recovery shares = permanent data loss</li>
              <li>You will keep recovery shares safe and inform your executor</li>
            </ul>
            <p className="mt-6 text-red-100">
              If you do not agree with these terms, <strong>DO NOT USE VIRASAT.</strong>
            </p>
          </div>

          {/* Contact */}
          <section className="mt-8">
            <h3 className="text-2xl font-bold text-white mb-4">Need Help?</h3>
            <p className="text-gray-300">
              If you have legal questions, contact a lawyer. For technical issues with Virasat, reach out to:
            </p>
            <div className="bg-slate-700/50 rounded p-4 mt-4">
              <p><strong>Email:</strong> legal@virasat.life</p>
              <p><strong>Address:</strong> Virasat, India</p>
              <p className="mt-4">
                See our <Link href="/terms" className="text-amber-400 hover:underline">Terms of Service</Link> and
                <Link href="/privacy" className="text-amber-400 hover:underline ml-1">Privacy Policy</Link> for more info.
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
